In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/McDonald_s_Reviews.csv', encoding='latin1')

In [ ]:
df.head()

reviewer_id  store_name              category  \
0            1  McDonald's  Fast food restaurant   
1            2  McDonald's  Fast food restaurant   
2            3  McDonald's  Fast food restaurant   
3            4  McDonald's  Fast food restaurant   
4            5  McDonald's  Fast food restaurant   

                                       store_address  latitude   longitude  \
0  13749 US-183 Hwy, Austin, TX 78750, United States  30.460718 -97.792874   
1  13749 US-183 Hwy, Austin, TX 78750, United States  30.460718 -97.792874   
2  13749 US-183 Hwy, Austin, TX 78750, United States  30.460718 -97.792874   
3  13749 US-183 Hwy, Austin, TX 78750, United States  30.460718 -97.792874   
4  13749 US-183 Hwy, Austin, TX 78750, United States  30.460718 -97.792874   

  rating_count   review_time  \
0        1,240  3 months ago   
1        1,240    5 days ago   
2        1,240    5 days ago   
3        1,240   a month ago   
4        1,240  2 months ago   

                                              review   rating  
0  Why does it look like someone spit on my food?...   1 star  
1  It'd McDonalds. It is what it is as far as the...  4 stars  
2  Made a mobile order got to the speaker and che...   1 star  
3  My mc. Crispy chicken sandwich was ���ï¿...  5 stars  
4  I repeat my order 3 times in the drive thru, a...   1 star

In [ ]:
df['category'].value_counts()

category
Fast food restaurant    33396
Name: count, dtype: int64

In [ ]:
df.drop(['store_name', 'category', 'reviewer_id'], axis=1, inplace=True)

In [ ]:
df['latitude'] = df['latitude ']
df.drop('latitude ', axis = 1)

store_address  longitude  \
0      13749 US-183 Hwy, Austin, TX 78750, United States -97.792874   
1      13749 US-183 Hwy, Austin, TX 78750, United States -97.792874   
2      13749 US-183 Hwy, Austin, TX 78750, United States -97.792874   
3      13749 US-183 Hwy, Austin, TX 78750, United States -97.792874   
4      13749 US-183 Hwy, Austin, TX 78750, United States -97.792874   
...                                                  ...        ...   
33391  3501 Biscayne Blvd, Miami, FL 33137, United St... -80.189098   
33392  3501 Biscayne Blvd, Miami, FL 33137, United St... -80.189098   
33393  3501 Biscayne Blvd, Miami, FL 33137, United St... -80.189098   
33394  3501 Biscayne Blvd, Miami, FL 33137, United St... -80.189098   
33395  3501 Biscayne Blvd, Miami, FL 33137, United St... -80.189098   

      rating_count   review_time  \
0            1,240  3 months ago   
1            1,240    5 days ago   
2            1,240    5 days ago   
3            1,240   a month ago   
4            1,240  2 months ago   
...            ...           ...   
33391        2,810   4 years ago   
33392        2,810    a year ago   
33393        2,810    a year ago   
33394        2,810   5 years ago   
33395        2,810   2 years ago   

                                                  review   rating   latitude  
0      Why does it look like someone spit on my food?...   1 star  30.460718  
1      It'd McDonalds. It is what it is as far as the...  4 stars  30.460718  
2      Made a mobile order got to the speaker and che...   1 star  30.460718  
3      My mc. Crispy chicken sandwich was ���ï¿...  5 stars  30.460718  
4      I repeat my order 3 times in the drive thru, a...   1 star  30.460718  
...                                                  ...      ...        ...  
33391                        They treated me very badly.   1 star  25.810000  
33392                           The service is very good  5 stars  25.810000  
33393                         To remove hunger is enough  4 stars  25.810000  
33394  It's good, but lately it has become very expen...  5 stars  25.810000  
33395                          they took good care of me  5 stars  25.810000  

[33396 rows x 7 columns]

In [ ]:
df.duplicated().sum()
df.drop_duplicates(inplace=True)

In [ ]:
df[df['latitude'].isna() | df['longitude'].isna()]['store_address'].unique()


array(['2476 Kal���������������'],
      dtype=object)

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df = df.dropna(subset=['latitude', 'longitude'])
df.isna().sum()

store_address    0
latitude         0
longitude        0
rating_count     0
review_time      0
review           0
rating           0
latitude         0
dtype: int64

In [ ]:
df.drop('store_address', axis=1, inplace=True)

In [ ]:
import re

def clean_text(text):
    text = str(text).lower()                           # lowercase
    text = re.sub(r"http\S+|www\.\S+", " ", text)      # remove URLs
    text = re.sub(r"[^a-z0-9\s]", " ", text)           # keep only letters/numbers
    text = re.sub(r"\s+", " ", text).strip()           # normalize spaces
    return text

# Apply cleaning
df["clean_text"] = df["review"].apply(clean_text)

# Show samples
df[["review", "clean_text"]].head(10)


review  \
0  Why does it look like someone spit on my food?...   
1  It'd McDonalds. It is what it is as far as the...   
2  Made a mobile order got to the speaker and che...   
3  My mc. Crispy chicken sandwich was ���ï¿...   
4  I repeat my order 3 times in the drive thru, a...   
5  I work for door dash and they locked us all ou...   
6  If I  could give this location a zero on custo...   
7  Came in and ordered a Large coffee w/no ice. T...   
8  Went thru drive thru. Ordered. Getting home no...   
9  I'm not really a huge fan of fast food, but I ...   

                                          clean_text  
0  why does it look like someone spit on my food ...  
1  it d mcdonalds it is what it is as far as the ...  
2  made a mobile order got to the speaker and che...  
3  my mc crispy chicken sandwich was customer ser...  
4  i repeat my order 3 times in the drive thru an...  
5  i work for door dash and they locked us all ou...  
6  if i could give this location a zero on custom...  
7  came in and ordered a large coffee w no ice th...  
8  went thru drive thru ordered getting home noti...  
9  i m not really a huge fan of fast food but i h...

In [ ]:
df_copy = df

In [ ]:
!pip install gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 79.2 MB/s eta 0:00:00


In [ ]:
# simple tokenization by splitting
sentences = df['clean_text'].apply(lambda x: x.split()).tolist()


In [ ]:
import gensim.downloader as api
from gensim.models import Word2Vec

w2v_model = Word2Vec(
    sentences,
    vector_size=100,   # dimension of embedding
    window=5,
    min_count=3,       # ignore rare words
    workers=4,
    sg=1               # 1 = skip-gram (better), 0 = CBOW
)


In [ ]:
def get_review_vector(tokens, model, vector_size=100):
    vecs = []
    for word in tokens:
        if word in model.wv:
            vecs.append(model.wv[word])
    if len(vecs) == 0:
        return np.zeros(vector_size)
    return np.mean(vecs, axis=0)   # average word vectors


In [ ]:
X_w2v = np.array([get_review_vector(sent, w2v_model, 100) for sent in sentences])
y = df['rating'].values

In [ ]:
print(X_w2v.shape)

(28543, 100)


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

X_train, X_test, y_train, y_test = train_test_split(
    X_w2v, y, test_size=0.2, stratify=y, random_state=42
)

clf = SVC(kernel='rbf', C=5, gamma='scale')
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))


Accuracy: 0.6118409528814153
              precision    recall  f1-score   support

      1 star       0.66      0.92      0.77      1813
     2 stars       0.68      0.06      0.11       565
     3 stars       0.46      0.36      0.40       789
     4 stars       0.46      0.20      0.28       917
     5 stars       0.62      0.82      0.71      1625

    accuracy                           0.61      5709
   macro avg       0.58      0.47      0.45      5709
weighted avg       0.59      0.61      0.56      5709



In [ ]:
# convert labels 1..5 -> 0..4
y0 = y - 1   # if y is a numpy array or pandas Series
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
X = X_w2v

# train/test split (use y0 for stratify)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y0, test_size=0.2,
                                                    stratify=y0, random_state=42)

# XGBoost (keep num_class = 5)
from xgboost import XGBClassifier
xgb = XGBClassifier(objective='multi:softprob', num_class=5,
                    eval_metric='mlogloss', use_label_encoder=False,
                    n_jobs=-1, tree_method='hist', random_state=42)

xgb.fit(X_train, y_train, eval_set=[(X_test, y_test)], verbose=10)

# predict and convert back to original labels (1..5)
y_pred0 = xgb.predict(X_test)       # 0..4
y_pred = y_pred0 + 1                # back to 1..5

# evaluate
from sklearn.metrics import accuracy_score, classification_report
print("Accuracy:", accuracy_score(y_test + 1, y_pred))  # or compare appropriately
print(classification_report(y_test + 1, y_pred))

print("R2 score:", r2_score(y_test + 1, y_pred))


/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [06:37:55] WARNING: /workspace/src/learner.cc:790: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


[0]	validation_0-mlogloss:1.41687
[10]	validation_0-mlogloss:1.06256
[20]	validation_0-mlogloss:0.99571
[30]	validation_0-mlogloss:0.96483
[40]	validation_0-mlogloss:0.94419
[50]	validation_0-mlogloss:0.93056
[60]	validation_0-mlogloss:0.91907
[70]	validation_0-mlogloss:0.91014
[80]	validation_0-mlogloss:0.90480
[90]	validation_0-mlogloss:0.90278
[99]	validation_0-mlogloss:0.90270
Accuracy: 0.6768260641093011
              precision    recall  f1-score   support

           1       0.74      0.90      0.81      1813
           2       0.70      0.35      0.47       565
           3       0.56      0.43      0.48       789
           4       0.56      0.41      0.47       917
           5       0.68      0.81      0.74      1625

    accuracy                           0.68      5709
   macro avg       0.65      0.58      0.60      5709
weighted avg       0.66      0.68      0.66      5709

R2 score: 0.5717445708208765


In [ ]:
import gensim.downloader as api
from gensim.models import Word2Vec

vectorizer = Word2Vec()

# vectorizer = TfidfVectorizer(
#     max_features=5000,       # top 5000 important words
#     ngram_range=(1,2),       # unigrams + bigrams
#     stop_words='english'     # remove common words
# )

X = vectorizer.fit_transform(df['clean_text'])
y = df['rating']

print("TF-IDF matrix shape:", X.shape)


ModuleNotFoundError: No module named 'gensim'

In [ ]:
print(pd.Series(y).value_counts().sort_index())


rating
1    9062
2    2825
3    3947
4    4585
5    8124
Name: count, dtype: int64


In [ ]:
from sklearn.model_selection import train_test_split

# 1) Quick class-balance check (important)
print("Label distribution (full dataset):")
print(pd.Series(y).value_counts().sort_index())

# 2) Stratified train-test split
# - test_size=0.2 gives 80% train / 20% test
# - random_state for reproducibility
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

# 3) Confirm sizes
print("\nTrain size:", X_train.shape[0])
print("Test size :", X_test.shape[0])

# 4) Optional quick sanity: class distribution in train/test
print("\nTrain label distribution:")
print(pd.Series(y_train).value_counts().sort_index())
print("\nTest label distribution:")
print(pd.Series(y_test).value_counts().sort_index())



Label distribution (full dataset):
rating
1    9062
2    2825
3    3947
4    4585
5    8124
Name: count, dtype: int64

Train size: 22834
Test size : 5709

Train label distribution:
rating
1    7249
2    2260
3    3158
4    3668
5    6499
Name: count, dtype: int64

Test label distribution:
rating
1    1813
2     565
3     789
4     917
5    1625
Name: count, dtype: int64


In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

# baseline linear SVM
baseline_svm = SVC(kernel='linear', C=1, random_state=42)

# train it
baseline_svm.fit(X_train, y_train)

# predict on test set
y_pred_baseline = baseline_svm.predict(X_test)

# evaluate
print("Baseline Linear SVM Accuracy:", accuracy_score(y_test, y_pred_baseline))

print("\nClassification Report:")
print(classification_report(y_test, y_pred_baseline))


Baseline Linear SVM Accuracy: 0.6177964617270976

Classification Report:
              precision    recall  f1-score   support

           1       0.68      0.89      0.77      1813
           2       0.49      0.13      0.20       565
           3       0.47      0.34      0.40       789
           4       0.47      0.28      0.35       917
           5       0.63      0.80      0.71      1625

    accuracy                           0.62      5709
   macro avg       0.55      0.49      0.49      5709
weighted avg       0.59      0.62      0.58      5709



In [ ]:
df['rating'] = df['rating'].astype(str).str.extract(r'(\d)').astype(int)
df['rating'].unique()

array([1, 4, 5, 2, 3])

In [ ]:
# quick_grid_search.py  (paste into your notebook)
from sklearn.model_selection import GridSearchCV, StratifiedKFold, train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import joblib

# assume X, y already exist (TF-IDF on df['clean_text'], df['rating'] numeric)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

param_grid = [
    {'kernel': ['linear'], 'C': [1, 10]},
    {'kernel': ['rbf'], 'C': [1], 'gamma': ['scale']},
    {'kernel': ['poly'], 'C': [1], 'degree': [2]}
]

cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)
grid = GridSearchCV(SVC(random_state=42), param_grid, cv=cv, scoring='accuracy', n_jobs=-1, verbose=1)
grid.fit(X_train, y_train)

print("Best params:", grid.best_params_)
print("Best cross-val score:", grid.best_score_)

best = grid.best_estimator_
y_pred = best.predict(X_test)
print("Test accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred, labels=[1,2,3,4,5]))

# save
joblib.dump(best, "svm_quick_grid_best.joblib")


Fitting 3 folds for each of 4 candidates, totalling 12 fits
Best params: {'C': 1, 'gamma': 'scale', 'kernel': 'rbf'}
Best cross-val score: 0.6315141039030937
Test accuracy: 0.6642143983184445
              precision    recall  f1-score   support

           1       0.70      0.92      0.80      1813
           2       0.85      0.24      0.37       565
           3       0.57      0.40      0.47       789
           4       0.58      0.33      0.42       917
           5       0.65      0.84      0.74      1625

    accuracy                           0.66      5709
   macro avg       0.67      0.55      0.56      5709
weighted avg       0.66      0.66      0.63      5709

Confusion matrix:
 [[1674    7   47   17   68]
 [ 316  135   45   17   52]
 [ 226   16  313   75  159]
 [  86    1   85  301  444]
 [  86    0   57  113 1369]]


['svm_quick_grid_best.joblib']

Expected question -
1. What was the objective of your Food Review Classification project?

Expected answer:

“To classify McDonald’s customer reviews into ratings using NLP + ML.
The goal was to preprocess raw text, extract meaningful features using TF-IDF, and train an SVM classifier, followed by cross-validation and hyperparameter tuning.”

2. Why did you choose the McDonald's dataset?

Expected answer:

“It contains real customer reviews, is text-heavy, and suitable for NLP tasks like sentiment/rating prediction.”

3. What kind of problem is this?

👉 Multi-class text classification (1 to 5-star ratings).

4. What were your input features and target?

Input: clean_text

Target: rating

You can mention you removed:

reviewer ID

store name

store address

latitude

longitude

other irrelevant metadata

#SECTION 2 — Data Preprocessing Questions
5. What preprocessing steps did you apply to the text?

Answer clearly:

Lowercasing

Removing URLs

Removing punctuation / special chars

Removing extra spaces

Tokenization
(And optionally stopwords via TF-IDF)

6. Why did you clean text before TF-IDF?

Expected:

“Noisy text increases vocabulary size, reduces model accuracy, and slows training. Cleaning improves signal-to-noise ratio.”

8. Did you face class imbalance? How did you handle it?

Your dataset is slightly imbalanced but OK.
Say:

“Class distribution was acceptable and stratified splitting preserved balance.”

7. Why did you drop store name/store address/geo features?

“These features don’t affect textual sentiment and add noise.
TF-IDF + SVM works best with clean textual features.”

9. Why did you choose TF-IDF? Not Bag of Words?

Best answer:

“TF-IDF downweights common words and highlights informative words.
It represents text better than BoW for classification tasks.”

10. What hyperparameters did you use in TF-IDF?

You used:

max_features=5000

ngram_range = (1,2)

stop_words='english'

Explain why:

“Bigrams capture short phrases like ‘not good’ which improve performance.”



#Model selection questions
11. Why did you choose SVM?

Perfect answer:

“SVM is powerful for high-dimensional sparse text data.
TF-IDF features are ideal for linear decision boundaries.”

12. Why did you try different kernels (linear, RBF, polynomial)?

“To evaluate different decision boundary shapes and find the one best suited for the text’s structure.”

13. Which kernel performed the best? Why?

Your answer depends on results, but generally:

“Linear kernel typically performed best because TF-IDF vectors are high-dimensional and nearly linearly separable.”

#Cross Validation & Hyperparameter Tuning
14. Why did you perform cross-validation?

“To get a more reliable estimate of model performance and reduce variance.
It gives a stable metric that does not depend on a single split.”

15. What hyperparameters did you tune in SVM?

C

kernel

gamma (for RBF)

degree (for polynomial)

Explain:

“C controls margin softness, gamma controls curvature, degree controls polynomial complexity.”

16. How did hyperparameter tuning improve accuracy?

Answer:

“GridSearchCV found the optimal combination of kernel and C, improving generalization.”

#Evaluation Questions
17. What metrics did you use to evaluate the model?

Accuracy

Classification report (precision, recall, F1-score)

Confusion matrix

Say:

“Multi-class classification requires granular per-class evaluation.”

#Deployment / Script Questions
1. How did you save the trained model? Why joblib?

“I used joblib because it efficiently saves large NumPy arrays inside TF-IDF + SVM models.” TO load them use joblin.load function("svm_model.pkl").“The prediction script transforms new text using TF-IDF and applies the trained SVM to generate ratings.”


2. Why did you use os module?

“To manage file paths and ensure the script safely loads files.”


#Improvements
1) Increase TF-IDF richness

You originally used:

max_features = 5000

ngram_range = (1,2)

Better improvements:

Increase to 10,000–50,000 features

Try (1,3) to capture “not at all good” patterns

Add sublinear_tf=True

Why it helps:
Better phrase modeling → higher classification signal

2. Switch to TF-IDF Weighted Word2Vec

Instead of simple averaging:

document_vector = mean(embedding(word))


Use:

weighted_vector = sum(TFIDF(word) × embedding(word))


Why it helps:
Important words get more weight; stopwords get almost zero.

3. Use FastText instead of Word2Vec

FastText learns embeddings for:

whole words

subword character n-grams

Advantages:

handles misspellings

handles rare words better

Perfect for user reviews with slang and typos.

4) Use Pretrained Embeddings

Instead of training your own:

GloVe 840B tokens

Google Word2Vec pretrained

FastText pretrained (Crawl/CC)

These capture MUCH deeper semantic meaning → boosts accuracy directly.

5) Use Transformer-Based Embeddings (Best Upgrade)

Use:

BERT

DistilBERT

RoBERTa

MPNet

Sentence-BERT (SBERT)

These give contextual embeddings that capture meaning far better than TF-IDF/W2V.

Expected accuracy jump on 5-class rating prediction:

TF-IDF + SVM → 62–66%

Word2Vec → 65–72%

SBERT + Logistic Regression → 75–82%

Full BERT fine-tuned → 85–90%

You can say:

“The inherent difficulty of mapping reviews to exact star ratings requires contextual embeddings like BERT. This would significantly improve performance over classical NLP methods.”

Improve Classification Models
6) Switch from SVC(kernel='linear') → LinearSVC

Advantages:

10–50× faster

Often better generalization

Handles sparse high-dimensional vectors better

This is the industry standard for text classification.

7) Logistic Regression (Strong Baseline)

Often more stable than SVM when classes overlap heavily.

Try:

C tuning

class_weight='balanced'

solver='liblinear' or 'saga'

8) Use Ensemble Models
XGBoost (you tried this)

Works well with:

dense embeddings (Word2Vec, SBERT)

nonlinear patterns between review words and rating

Tune:

max_depth

n_estimators

learning_rate

colsample_bytree

10) Deep Learning CNN/LSTM

For sequence modeling:

TextCNN

BiLSTM

GRU

RCNN (Recurrent CNN)

Better performance than TF-IDF but less than BERT.

8.3 — Improve the Task Itself (Reframing the Problem)
11) Convert 5-star classification → Sentiment classification

Example:

negative = 1,2

neutral = 3

positive = 4,5

Accuracy jumps to:
75–88% depending on model

Why?
Star rating is subjective and ambiguous; sentiment is easier for models to infer.

13) Use Regression Instead of Classification

Ratings (1–5) are ordinal.

Better models:

Ordinal Regression (Logistic Regression)

XGBRegressor

SVR

Often gives more meaningful output.

8.4 — Improve Data Quality
14) Use Lemmatization / POS tagging

Better normalization of words:

“running” → “run”

“tasty” → “tasty”

Improves embeddings AND TF-IDF quality.

15) Handle emojis and emoticons

They have strong sentiment cues.

Example:

😡 → negative

😍 → positive

16) Remove extremely short reviews

1–2-word reviews add noise.

17) Spell correction (SymSpell / TextBlob)

Fix spelling errors that kill TF-IDF consistency.

🔵 8.5 — Improve Evaluation
18) Use better metrics for multi-class

Accuracy is misleading.
Use:

macro F1

confusion matrix

per-class recall

19) Stratified k-fold cross-validation

Better representation across classes vs train-test split.

20) Error analysis

Manually read misclassifications to:

adjust preprocessing

tune hyperparameters

understand ambiguous reviews

This is something real ML engineers always do.

#Project pitch
I developed a Food Review Classification system using the McDonald’s customer review dataset to predict star ratings from textual feedback. The project began with extensive text preprocessing—removing noise, normalizing text, and tokenizing reviews to prepare high-quality input for machine learning. I then used TF-IDF with unigram–bigram features to capture informative patterns and sentiment expressions in the reviews.

For the modeling stage, I implemented a Support Vector Machine classifier and performed stratified cross-validation across multiple kernels, including Linear, RBF, and Polynomial. I applied hyperparameter tuning using GridSearchCV to optimize C, gamma, and kernel choices for better generalization. The model was evaluated through accuracy, precision, recall, F1-scores, and confusion matrices to understand per-class performance and error patterns.

Finally, I created a reusable prediction script using joblib and os to load the trained classifier and TF-IDF vectorizer, allowing the system to generate predictions for any new set of reviews. Through this project, I gained hands-on experience with NLP preprocessing, feature engineering, SVM model selection, cross-validation, and deployment-ready inference workflows.